# Generated by Django 5.1.6 on 2025-04-12 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerwash', '0006_profile_address_profile_city_profile_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('marketing_comm', models.BooleanField(default=False)),
                ('enable_2fa', models.BooleanField(default=False)),
                ('language', models.CharField(choices=[('en', 'English'), ('es', 'Español'), ('fr', 'Français')], default='en', max_length=10)),
                ('time_zone', models.CharField(choices=[('UTC', 'UTC (GMT+0)'), ('EST', 'Eastern Time (GMT-5)'), ('PST', 'Pacific Time (GMT-8)')], default='UTC', max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
