# Generated by Django 5.2 on 2025-04-15 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerwash', '0007_usersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_type',
            field=models.CharField(choices=[('provider', 'Service Provider'), ('customer', 'Customer')], default='customer', max_length=20),
        ),
    ]
