# Generated by Django 6.0.dev20250303103700 on 2025-04-18 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerwash', '0007_usersettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('Mini Valet', 'Mini Valet'), ('Deep Clean', 'Deep Clean'), ('Premium Detail', 'Premium Detail')], max_length=20),
        ),
    ]
