# Generated by Django 6.0.dev20250303103700 on 2025-04-18 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerwash', '0008_alter_booking_service_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='location',
            field=models.CharField(choices=[('miami', 'Miami - 1250 Ocean Drive, Miami Beach, FL 33139'), ('orlando', 'Orlando - 8955 International Drive, Orlando, FL 32819'), ('tampa', 'Tampa - 615 Channelside Drive, Tampa, FL 33602'), ('jacksonville', 'Jacksonville - 2 Independent Drive, Jacksonville, FL 32202'), ('tallahassee', 'Tallahassee - 200 S Adams St, Tallahassee, FL 32301'), ('gainesville', 'Gainesville - 3600 SW Archer Rd, Gainesville, FL 32608'), ('pensacola', 'Pensacola - 400 Pensacola Beach Blvd, Gulf Breeze, FL 32561'), ('fortlauderdale', 'Fort Lauderdale - 1100 Seabreeze Blvd, Fort Lauderdale, FL 33316'), ('daytona', 'Daytona Beach - 1200 Main St, Daytona Beach, FL 32118'), ('keywest', 'Key West - 400 Front Street, Key West, FL 33040'), ('naples', 'Naples - 955 5th Avenue South, Naples, FL 34102')], default='miami', max_length=50),
            preserve_default=False,
        ),
    ]