# Generated by Django 6.0.dev20250303103700 on 2025-04-18 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('powerwash', '0009_booking_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='service_type',
            field=models.CharField(choices=[('mini', 'Mini Valet'), ('full', 'Full Valet'), ('premium', 'Wax and Polish')], max_length=20),
        ),
    ]
